name: Ejercicio 3: Multi-OS workflow

on:
  workflow_dispatch:

jobs:
  run-on-multiple-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Show OS
        run: echo "Running on ${{ matrix.os }}"

      - name: OS info
        shell: bash
        run: uname -a || ver
